##### 참고 : https://github.com/Tiiiger/bert_score

# 데이터셋 처리

### 생성된 가사 (G)

In [2]:
import pandas as pd

gen = pd.read_excel('./dataset/생성가사.xlsx')

In [3]:
iu_gen = gen['iu']

In [4]:
s_gen = gen['s']

In [5]:
mx_gen = gen['mx']

### 가수의 기존 가사 ('시작'이 들어간 가사 일부분을 모은 데이터셋)

##### 1) 아이유

In [6]:
import pandas as pd

D1 = pd.read_excel('./dataset/iu_start.xlsx') 
iu_D = D1['iu_lyrics']

In [7]:
len(iu_D)

32

##### 2) 선우정아

In [8]:
import pandas as pd

D2 = pd.read_excel('./dataset/s_start.xlsx') 
s_D = D2['s_lyrics']

In [9]:
s_D[0]

'시간이 낡았고모든 게 변했어도있잖아 우리는그냥 이대로 살자대단치 않아도둘이서 매일을조그맣게그림 같은 집을 짓진 못했지만It’s not romantic to cleanthe bathroom is it Hon’맘껏 뒹굴거릴 수 있으니까여긴 완전한 둘의 세계야저 바깥에서는감춰 숨겨두었던 모든 것조금 더 알을래 가까이너만 느껴지게 가까이있잖아 '

##### 3) 몬스타엑스

In [10]:
import pandas as pd

D3 = pd.read_excel('./dataset/mx_start.xlsx') 
mx_D = D3['mx_lyrics'] 

In [11]:
mx_D[0]

"WE GO HIGH끌리는 대로 그냥 하면 돼소릴 높여 우린 하나가 돼어두웠던 시간은 꿈이 되어멋진 세상에 뛰어들어봐BOW WOW BOW WOWWE ARE SO DANGER(Refresh!)WA WA- WA WOO WA WA-WA WOO WA WAAH YEAH AH YEAHWE ARE SO DANGERWA WA- WA WOO WA WA-BOW WOW시원하게 즐겨 TASTE OF KOREAWE ARE SO DANGERWHAT'S UP WHAT'S WHAT'SWHAT'S UP WHAT'S WHAT'S WHAT'S UPUH UH UH UH UHBOW WOW BOW WOWWHAT'S UP WHAT'S WHAT'SWHAT'S UP WHAT'S WHAT'S WHAT'S UPUH UH UH UH UHWE ARE SO DANGER"

## ------------------------------------------------------------------------------------

# BERT SCORE 계산

# bert(D, G)

#####  1) 아이유-아이유

In [53]:
from bert_score import score

iu_iu = [[x,y] for x in iu_D for y in iu_gen]
len(iu_iu)

refs=[]
cands=[]
for i in range(len(iu_iu)):
    refs.append(iu_iu[i][0])
    cands.append(iu_iu[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)


Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 12.42 seconds, 12.88 sentences/sec


In [58]:
print(F1)
f1_tensor_iu=F1
iu_iu_array = f1_tensor.numpy()
array.mean()

tensor([0.6515, 0.5779, 0.5526, 0.6216, 0.6385, 0.6040, 0.5242, 0.5375, 0.6333,
        0.6068, 0.6358, 0.5611, 0.5486, 0.5960, 0.6304, 0.6281, 0.5573, 0.5554,
        0.5927, 0.6094, 0.6164, 0.5377, 0.5421, 0.6421, 0.6206, 0.6271, 0.5624,
        0.5478, 0.5955, 0.6103, 0.5919, 0.5291, 0.5423, 0.5746, 0.5820, 0.6293,
        0.5753, 0.5721, 0.5871, 0.6074, 0.6299, 0.5784, 0.5845, 0.5976, 0.6328,
        0.6285, 0.6045, 0.5769, 0.5742, 0.6288, 0.6131, 0.5775, 0.5684, 0.5842,
        0.6180, 0.5943, 0.5376, 0.5620, 0.6016, 0.5846, 0.6111, 0.5564, 0.5552,
        0.5944, 0.6194, 0.6229, 0.5549, 0.5707, 0.5905, 0.6308, 0.6483, 0.5891,
        0.5851, 0.6235, 0.6459, 0.6108, 0.6038, 0.5796, 0.5682, 0.6158, 0.6343,
        0.5696, 0.5836, 0.6116, 0.6261, 0.6472, 0.5654, 0.5789, 0.6276, 0.6285,
        0.6076, 0.5507, 0.5564, 0.6062, 0.6139, 0.6386, 0.5837, 0.5715, 0.6290,
        0.6484, 0.5744, 0.5117, 0.5268, 0.5598, 0.5723, 0.6506, 0.5784, 0.5876,
        0.6028, 0.6418, 0.5910, 0.5675, 

0.5915971

##### 2) 아이유-선우정아

In [62]:
from bert_score import score

iu_s = [[x,y] for x in iu_D for y in s_gen]
len(iu_s)

refs=[]
cands=[]
for i in range(len(iu_s)):
    refs.append(iu_s[i][0])
    cands.append(iu_s[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)


Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 22.96 seconds, 6.97 sentences/sec


In [63]:
print(F1)
f1_tensor_iu_s=F1
iu_s_array = f1_tensor_iu_s.numpy()
iu_s_array.mean()

tensor([0.5883, 0.6344, 0.5952, 0.6299, 0.5428, 0.5683, 0.5915, 0.5678, 0.5875,
        0.5009, 0.5945, 0.6257, 0.5864, 0.6027, 0.5294, 0.5593, 0.6108, 0.5697,
        0.5985, 0.5077, 0.5457, 0.6023, 0.5547, 0.5947, 0.5001, 0.5625, 0.6139,
        0.5624, 0.6076, 0.5095, 0.5385, 0.5892, 0.5613, 0.5878, 0.4923, 0.5811,
        0.6082, 0.5848, 0.6156, 0.5195, 0.5750, 0.6188, 0.5880, 0.6240, 0.5310,
        0.5599, 0.6623, 0.5881, 0.5733, 0.5612, 0.5701, 0.5937, 0.5655, 0.6072,
        0.5313, 0.5494, 0.5834, 0.5419, 0.5979, 0.5004, 0.5656, 0.5898, 0.5586,
        0.6001, 0.5155, 0.5852, 0.5997, 0.5623, 0.6325, 0.5293, 0.5993, 0.6115,
        0.5907, 0.6523, 0.5372, 0.6025, 0.6134, 0.5923, 0.5849, 0.5510, 0.5958,
        0.6068, 0.5819, 0.6178, 0.5529, 0.5695, 0.6214, 0.5745, 0.6155, 0.5310,
        0.5596, 0.5989, 0.5617, 0.6210, 0.5226, 0.5733, 0.6043, 0.5836, 0.6164,
        0.5219, 0.5419, 0.5622, 0.5572, 0.5677, 0.4756, 0.6137, 0.6090, 0.6087,
        0.6200, 0.5441, 0.5688, 0.5804, 

0.5738945

##### 3) 아이유-몬엑

In [64]:
from bert_score import score

iu_mx = [[x,y] for x in iu_D for y in mx_gen]
len(iu_s)

refs=[]
cands=[]
for i in range(len(iu_mx)):
    refs.append(iu_mx[i][0])
    cands.append(iu_mx[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)


Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 22.44 seconds, 7.13 sentences/sec


In [65]:
print(F1)
f1_tensor_iu_mx=F1
iu_mx_array = f1_tensor_iu_mx.numpy()
iu_mx_array.mean()

tensor([0.5590, 0.5720, 0.5995, 0.5675, 0.5615, 0.5040, 0.5316, 0.5604, 0.5378,
        0.5350, 0.5519, 0.5546, 0.5864, 0.5605, 0.5686, 0.5397, 0.5367, 0.5698,
        0.5402, 0.5385, 0.5210, 0.5232, 0.5464, 0.5315, 0.5212, 0.5334, 0.5368,
        0.5585, 0.5372, 0.5422, 0.5014, 0.5137, 0.5642, 0.5259, 0.5419, 0.5509,
        0.5546, 0.5838, 0.5587, 0.5616, 0.5556, 0.5638, 0.5886, 0.5693, 0.5582,
        0.5601, 0.5692, 0.5709, 0.5679, 0.5521, 0.5468, 0.5613, 0.5797, 0.5657,
        0.5582, 0.5258, 0.5241, 0.5444, 0.5188, 0.5145, 0.5179, 0.5417, 0.5673,
        0.5600, 0.5674, 0.5360, 0.5556, 0.5891, 0.5588, 0.5537, 0.5600, 0.5705,
        0.6009, 0.5792, 0.5883, 0.5613, 0.5863, 0.5908, 0.5683, 0.5761, 0.5615,
        0.5578, 0.5925, 0.5687, 0.5534, 0.5323, 0.5407, 0.5674, 0.5555, 0.5413,
        0.5249, 0.5378, 0.5777, 0.5526, 0.5479, 0.5390, 0.5532, 0.5770, 0.5669,
        0.5480, 0.4837, 0.5138, 0.5626, 0.5428, 0.5525, 0.5752, 0.5792, 0.6017,
        0.5910, 0.5759, 0.5320, 0.5559, 

0.55090857

##### 4) 선우정아- 아이유

In [66]:
from bert_score import score

s_iu = [[x,y] for x in s_D for y in iu_gen]
len(s_iu)

refs=[]
cands=[]
for i in range(len(s_iu)):
    refs.append(s_iu[i][0])
    cands.append(s_iu[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)


Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 11.28 seconds, 12.85 sentences/sec


In [67]:
print(F1)
f1_tensor_s_iu=F1
s_iu_array = f1_tensor_s_iu.numpy()
s_iu_array.mean()

tensor([0.5952, 0.5217, 0.5520, 0.5850, 0.5803, 0.6086, 0.5266, 0.5289, 0.5690,
        0.6043, 0.6257, 0.5844, 0.5971, 0.6068, 0.6277, 0.6627, 0.6163, 0.5936,
        0.6005, 0.6369, 0.6333, 0.5570, 0.5594, 0.5842, 0.6278, 0.5905, 0.5333,
        0.5560, 0.6074, 0.5793, 0.5731, 0.5211, 0.5263, 0.5945, 0.5680, 0.6288,
        0.5667, 0.5688, 0.6077, 0.6389, 0.6043, 0.5579, 0.5462, 0.5763, 0.6172,
        0.6054, 0.5784, 0.5575, 0.5936, 0.6116, 0.6243, 0.6280, 0.5981, 0.5779,
        0.6071, 0.6140, 0.5507, 0.5498, 0.5790, 0.5987, 0.6286, 0.5478, 0.5573,
        0.6347, 0.6173, 0.6264, 0.5781, 0.5663, 0.6042, 0.6251, 0.6185, 0.5556,
        0.5684, 0.6018, 0.6139, 0.5900, 0.5632, 0.5448, 0.6318, 0.5954, 0.6099,
        0.5380, 0.5432, 0.5865, 0.6048, 0.6321, 0.5664, 0.5681, 0.6081, 0.6399,
        0.6428, 0.6441, 0.6043, 0.6152, 0.6280, 0.5646, 0.5385, 0.5511, 0.5933,
        0.5715, 0.6077, 0.5918, 0.5788, 0.5999, 0.6146, 0.6270, 0.5570, 0.5723,
        0.6040, 0.6105, 0.6158, 0.5582, 

0.5910249

##### 5) 선우정아 - 선우정아

In [68]:
from bert_score import score

s_s = [[x,y] for x in s_D for y in s_gen]
len(s_s)

refs=[]
cands=[]
for i in range(len(s_s)):
    refs.append(s_s[i][0])
    cands.append(s_s[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)


Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 21.39 seconds, 6.78 sentences/sec


In [69]:
print(F1)
f1_tensor_s_s=F1
s_s_array = f1_tensor_s_s.numpy()
s_s_array.mean()

tensor([0.5485, 0.5857, 0.5662, 0.5767, 0.4940, 0.5973, 0.5994, 0.5694, 0.5977,
        0.5106, 0.5808, 0.6465, 0.5828, 0.6175, 0.5586, 0.5891, 0.6429, 0.5990,
        0.6207, 0.5738, 0.5925, 0.6252, 0.5805, 0.6319, 0.5357, 0.5486, 0.5627,
        0.5595, 0.5790, 0.4979, 0.5548, 0.5584, 0.5529, 0.5681, 0.4885, 0.5825,
        0.6316, 0.5779, 0.6141, 0.5348, 0.6166, 0.5818, 0.6270, 0.5988, 0.5317,
        0.5724, 0.6216, 0.5705, 0.6091, 0.5393, 0.5785, 0.6111, 0.5985, 0.6076,
        0.5861, 0.6019, 0.5919, 0.5969, 0.6207, 0.5195, 0.5494, 0.5998, 0.5658,
        0.5837, 0.4999, 0.5883, 0.6027, 0.5666, 0.6211, 0.5324, 0.5760, 0.6009,
        0.5663, 0.6227, 0.5344, 0.5464, 0.5867, 0.5516, 0.5871, 0.5196, 0.5884,
        0.6121, 0.5798, 0.6135, 0.5196, 0.5838, 0.6310, 0.5769, 0.6119, 0.5345,
        0.5905, 0.6186, 0.6134, 0.6426, 0.5854, 0.5620, 0.5659, 0.5763, 0.5618,
        0.5035, 0.5699, 0.5935, 0.5878, 0.6045, 0.5482, 0.5559, 0.6098, 0.5650,
        0.5979, 0.5357, 0.5923, 0.5916, 

0.57974726

##### 6) 선우정아 - 몬엑

In [70]:
from bert_score import score

s_mx = [[x,y] for x in s_D for y in mx_gen]
len(s_mx)

refs=[]
cands=[]
for i in range(len(s_mx)):
    refs.append(s_mx[i][0])
    cands.append(s_mx[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)


Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 21.77 seconds, 6.66 sentences/sec


In [71]:
print(F1)
f1_tensor_s_mx=F1
s_mx_array = f1_tensor_s_mx.numpy()
s_mx_array.mean()

tensor([0.5187, 0.5322, 0.5465, 0.5325, 0.5305, 0.5111, 0.5675, 0.5926, 0.5666,
        0.5660, 0.5606, 0.5827, 0.5932, 0.5759, 0.5619, 0.5749, 0.5923, 0.5940,
        0.6019, 0.5791, 0.5497, 0.5768, 0.6005, 0.5678, 0.5699, 0.5106, 0.5248,
        0.5384, 0.5253, 0.5144, 0.5037, 0.5254, 0.5414, 0.5158, 0.5315, 0.5473,
        0.5622, 0.5799, 0.5621, 0.5576, 0.5528, 0.5679, 0.6105, 0.5904, 0.5721,
        0.5438, 0.5460, 0.5640, 0.5579, 0.5478, 0.5829, 0.5870, 0.5778, 0.5799,
        0.5803, 0.5305, 0.5932, 0.6075, 0.5806, 0.5739, 0.5157, 0.5381, 0.5605,
        0.5209, 0.5239, 0.5463, 0.5550, 0.5737, 0.5519, 0.5670, 0.5319, 0.5554,
        0.5794, 0.5548, 0.5444, 0.5230, 0.5212, 0.5355, 0.5262, 0.5207, 0.5215,
        0.5876, 0.5925, 0.5724, 0.5620, 0.5471, 0.5604, 0.5798, 0.5610, 0.5570,
        0.5960, 0.6019, 0.6075, 0.6311, 0.5918, 0.5189, 0.5404, 0.5627, 0.5370,
        0.5556, 0.5682, 0.5843, 0.5757, 0.5833, 0.5689, 0.5337, 0.5403, 0.5590,
        0.5461, 0.5301, 0.5403, 0.5645, 

0.5580295

##### 7) 몬엑 - 아이유

In [72]:
from bert_score import score

mx_iu = [[x,y] for x in mx_D for y in iu_gen]
len(mx_iu)

refs=[]
cands=[]
for i in range(len(mx_iu)):
    refs.append(mx_iu[i][0])
    cands.append(mx_iu[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)


Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 21.78 seconds, 10.79 sentences/sec


In [73]:
print(F1)
f1_tensor_mx_iu=F1
mx_iu_array = f1_tensor_mx_iu.numpy()
mx_iu_array.mean()

tensor([0.5812, 0.5739, 0.5431, 0.5541, 0.5853, 0.5823, 0.5148, 0.5311, 0.5641,
        0.5797, 0.6102, 0.5480, 0.5373, 0.6161, 0.6114, 0.5831, 0.5274, 0.5262,
        0.5729, 0.5808, 0.6133, 0.5318, 0.5350, 0.5708, 0.5974, 0.5873, 0.5334,
        0.5383, 0.5867, 0.5897, 0.6227, 0.5483, 0.5594, 0.6014, 0.6098, 0.5990,
        0.5433, 0.5337, 0.5800, 0.5964, 0.6411, 0.5583, 0.5671, 0.6074, 0.6309,
        0.5985, 0.5279, 0.5355, 0.6335, 0.5982, 0.6484, 0.5664, 0.5813, 0.6015,
        0.6292, 0.6034, 0.5318, 0.5331, 0.6286, 0.5952, 0.5857, 0.5309, 0.5319,
        0.5762, 0.5810, 0.5990, 0.5389, 0.5389, 0.5639, 0.5973, 0.6265, 0.5478,
        0.5407, 0.5847, 0.6181, 0.6194, 0.5454, 0.5569, 0.5887, 0.6087, 0.6070,
        0.5459, 0.5623, 0.5827, 0.6122, 0.6115, 0.5612, 0.5579, 0.5869, 0.6144,
        0.6134, 0.5642, 0.5516, 0.6518, 0.6126, 0.6067, 0.5516, 0.5555, 0.6085,
        0.6039, 0.5849, 0.5700, 0.5516, 0.6312, 0.5865, 0.5858, 0.5280, 0.5312,
        0.6206, 0.5809, 0.6255, 0.5626, 

0.5820906

##### 8) 몬엑 - 선우정아

In [75]:
from bert_score import score

mx_s = [[x,y] for x in mx_D for y in s_gen]
len(mx_s)

refs=[]
cands=[]
for i in range(len(mx_s)):
    refs.append(mx_s[i][0])
    cands.append(mx_s[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)


Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 33.24 seconds, 7.07 sentences/sec


In [76]:
print(F1)
f1_tensor_mx_s=F1
mx_s_array = f1_tensor_mx_s.numpy()
mx_s_array.mean()

tensor([0.6220, 0.5470, 0.5900, 0.5723, 0.5529, 0.5797, 0.5563, 0.5668, 0.5845,
        0.4815, 0.5781, 0.5920, 0.5703, 0.5831, 0.5007, 0.6045, 0.5758, 0.5984,
        0.5746, 0.4945, 0.5939, 0.5885, 0.5742, 0.6117, 0.5142, 0.5657, 0.5675,
        0.5706, 0.5725, 0.4849, 0.5779, 0.5986, 0.5627, 0.6020, 0.5187, 0.6157,
        0.5612, 0.5936, 0.5925, 0.5081, 0.5913, 0.6212, 0.5840, 0.6396, 0.5342,
        0.5518, 0.5899, 0.5599, 0.5849, 0.4905, 0.5669, 0.6369, 0.5898, 0.6007,
        0.5314, 0.5675, 0.5865, 0.5539, 0.5778, 0.4921, 0.5654, 0.5893, 0.5464,
        0.5734, 0.4986, 0.5809, 0.5684, 0.5735, 0.6009, 0.5155, 0.6013, 0.6032,
        0.6027, 0.6042, 0.5233, 0.5756, 0.6045, 0.5802, 0.6112, 0.5192, 0.5840,
        0.5911, 0.5822, 0.6061, 0.5165, 0.6253, 0.5910, 0.6052, 0.6281, 0.5235,
        0.5546, 0.5860, 0.5504, 0.5963, 0.4979, 0.5683, 0.6063, 0.5753, 0.6201,
        0.5248, 0.5441, 0.5865, 0.5808, 0.5726, 0.5251, 0.5524, 0.5612, 0.5484,
        0.5648, 0.5098, 0.5963, 0.6149, 

0.57341045

##### 9) 몬엑-몬엑

In [79]:
from bert_score import score

mx_mx = [[x,y] for x in mx_D for y in mx_gen]
len(mx_mx)

refs=[]
cands=[]
for i in range(len(mx_mx)):
    refs.append(mx_mx[i][0])
    cands.append(mx_mx[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)


Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 30.41 seconds, 7.73 sentences/sec


In [80]:
print(F1)
f1_tensor_mx_mx=F1
mx_mx_array = f1_tensor_mx_mx.numpy()
mx_mx_array.mean()

tensor([0.5657, 0.5802, 0.5825, 0.5947, 0.5600, 0.5042, 0.5417, 0.5875, 0.5669,
        0.5716, 0.5035, 0.5335, 0.5700, 0.5411, 0.5554, 0.5024, 0.5471, 0.5844,
        0.5613, 0.5792, 0.5220, 0.5640, 0.6074, 0.5664, 0.5807, 0.4958, 0.5302,
        0.5615, 0.5395, 0.5662, 0.5396, 0.5450, 0.5716, 0.5460, 0.5385, 0.5232,
        0.5584, 0.5948, 0.5742, 0.5892, 0.5512, 0.5727, 0.5975, 0.5826, 0.5657,
        0.5086, 0.5253, 0.5757, 0.5545, 0.5448, 0.5422, 0.5494, 0.5672, 0.5571,
        0.5387, 0.5104, 0.5260, 0.5545, 0.5456, 0.5548, 0.5124, 0.5222, 0.5489,
        0.5334, 0.5337, 0.5106, 0.5757, 0.5950, 0.5808, 0.5857, 0.5421, 0.5695,
        0.6146, 0.5823, 0.5832, 0.5239, 0.5413, 0.5877, 0.5490, 0.5555, 0.5576,
        0.5677, 0.5788, 0.5618, 0.5599, 0.5396, 0.5942, 0.6066, 0.5790, 0.6075,
        0.5251, 0.5223, 0.5527, 0.5275, 0.5285, 0.5269, 0.5508, 0.5792, 0.5484,
        0.5509, 0.5383, 0.5469, 0.5539, 0.5639, 0.5540, 0.5167, 0.5183, 0.5405,
        0.5231, 0.5189, 0.5418, 0.5590, 

0.55964804

# BERT(G,G)

In [83]:
from bert_score import score

iu_iu = [[x,y] for x in iu_gen for y in iu_gen]
len(iu_iu)

refs=[]
cands=[]
for i in range(len(iu_iu)):
    refs.append(iu_iu[i][0])
    cands.append(iu_iu[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)


Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 1.88 seconds, 13.32 sentences/sec


In [84]:
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

tensor([1.0000, 0.6282, 0.6238, 0.6341, 0.6938, 0.6282, 1.0000, 0.6230, 0.5828,
        0.6173, 0.6238, 0.6230, 1.0000, 0.5918, 0.6125, 0.6341, 0.5828, 0.5918,
        1.0000, 0.6382, 0.6938, 0.6173, 0.6125, 0.6382, 1.0000])


0.69963455

In [86]:
from bert_score import score

g_g = [[x,y] for x in iu_gen for y in mx_gen]
len(g_g)

refs=[]
cands=[]
for i in range(len(g_g)):
    refs.append(g_g[i][0])
    cands.append(g_g[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)


Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 6.07 seconds, 4.12 sentences/sec


In [87]:
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

tensor([0.5908, 0.5960, 0.6002, 0.6076, 0.5832, 0.5910, 0.6129, 0.5900, 0.6219,
        0.5999, 0.6029, 0.5842, 0.5649, 0.5839, 0.5575, 0.5524, 0.5634, 0.5760,
        0.5853, 0.5473, 0.5913, 0.6023, 0.6196, 0.6110, 0.5987])


0.58936876

In [88]:
from bert_score import score

g_g = [[x,y] for x in iu_gen for y in s_gen]
len(g_g)

refs=[]
cands=[]
for i in range(len(g_g)):
    refs.append(g_g[i][0])
    cands.append(g_g[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)


Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 6.01 seconds, 4.16 sentences/sec


In [89]:
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

tensor([0.6148, 0.6313, 0.6150, 0.6235, 0.5887, 0.6060, 0.6004, 0.6253, 0.5907,
        0.6247, 0.5820, 0.5702, 0.5870, 0.5843, 0.5820, 0.5887, 0.5835, 0.5735,
        0.6139, 0.5622, 0.6259, 0.6248, 0.6187, 0.6256, 0.5889])


0.60127753

In [90]:
from bert_score import score

g_g = [[x,y] for x in s_gen for y in iu_gen]
len(g_g)

refs=[]
cands=[]
for i in range(len(g_g)):
    refs.append(g_g[i][0])
    cands.append(g_g[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 6.43 seconds, 3.89 sentences/sec
tensor([0.6148, 0.6060, 0.5820, 0.5887, 0.6259, 0.6313, 0.6004, 0.5702, 0.5835,
        0.6248, 0.6150, 0.6253, 0.5870, 0.5735, 0.6187, 0.6235, 0.5907, 0.5843,
        0.6139, 0.6256, 0.5887, 0.6247, 0.5820, 0.5622, 0.5889])


0.60127753

In [91]:
from bert_score import score

g_g = [[x,y] for x in s_gen for y in s_gen]
len(g_g)

refs=[]
cands=[]
for i in range(len(g_g)):
    refs.append(g_g[i][0])
    cands.append(g_g[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 3.78 seconds, 6.61 sentences/sec
tensor([1.0000, 0.5792, 0.6673, 0.6108, 0.6054, 0.5792, 1.0000, 0.5906, 0.6056,
        0.5780, 0.6673, 0.5906, 1.0000, 0.6016, 0.5904, 0.6108, 0.6056, 0.6016,
        1.0000, 0.5613, 0.6054, 0.5780, 0.5904, 0.5613, 1.0000])


0.6792102

In [95]:
from bert_score import score

g_g = [[x,y] for x in s_gen for y in mx_gen]
len(g_g)

refs=[]
cands=[]
for i in range(len(g_g)):
    refs.append(g_g[i][0])
    cands.append(g_g[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 6.05 seconds, 4.13 sentences/sec
tensor([0.6050, 0.6606, 0.6356, 0.6570, 0.6285, 0.5613, 0.5839, 0.6018, 0.5760,
        0.5758, 0.6027, 0.6414, 0.6269, 0.6510, 0.6218, 0.5840, 0.5912, 0.6208,
        0.6021, 0.5861, 0.6093, 0.6211, 0.5932, 0.6287, 0.6025])


0.61073786

In [92]:
from bert_score import score

g_g = [[x,y] for x in mx_gen for y in iu_gen]
len(g_g)

refs=[]
cands=[]
for i in range(len(g_g)):
    refs.append(g_g[i][0])
    cands.append(g_g[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 5.82 seconds, 4.29 sentences/sec
tensor([0.5908, 0.5910, 0.6029, 0.5524, 0.5913, 0.5960, 0.6129, 0.5842, 0.5634,
        0.6023, 0.6002, 0.5900, 0.5649, 0.5760, 0.6196, 0.6076, 0.6219, 0.5839,
        0.5853, 0.6110, 0.5832, 0.5999, 0.5575, 0.5473, 0.5987])


0.58936876

In [96]:
from bert_score import score

g_g = [[x,y] for x in mx_gen for y in s_gen]
len(g_g)

refs=[]
cands=[]
for i in range(len(g_g)):
    refs.append(g_g[i][0])
    cands.append(g_g[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 5.99 seconds, 4.18 sentences/sec
tensor([0.6050, 0.5613, 0.6027, 0.5840, 0.6093, 0.6606, 0.5839, 0.6414, 0.5912,
        0.6211, 0.6356, 0.6018, 0.6269, 0.6208, 0.5932, 0.6570, 0.5760, 0.6510,
        0.6021, 0.6287, 0.6285, 0.5758, 0.6218, 0.5861, 0.6025])


0.61073786

In [97]:
from bert_score import score

g_g = [[x,y] for x in mx_gen for y in mx_gen]
len(g_g)

refs=[]
cands=[]
for i in range(len(g_g)):
    refs.append(g_g[i][0])
    cands.append(g_g[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 3.01 seconds, 8.32 sentences/sec
tensor([1.0000, 0.6333, 0.5868, 0.6211, 0.5789, 0.6333, 1.0000, 0.6303, 0.6725,
        0.6340, 0.5868, 0.6303, 1.0000, 0.6317, 0.6157, 0.6211, 0.6725, 0.6317,
        1.0000, 0.6218, 0.5789, 0.6340, 0.6157, 0.6218, 1.0000])


0.6980975

# BERT(D, D)

In [98]:
from bert_score import score

d_d = [[x,y] for x in iu_D for y in iu_D]
len(d_d)

refs=[]
cands=[]
for i in range(len(d_d)):
    refs.append(d_d[i][0])
    cands.append(d_d[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 7.97 seconds, 128.42 sentences/sec
tensor([1.0000, 0.6255, 0.6643,  ..., 0.9507, 0.6603, 1.0000])


0.6421359

In [99]:
from bert_score import score

d_d = [[x,y] for x in iu_D for y in s_D]
len(d_d)

refs=[]
cands=[]
for i in range(len(d_d)):
    refs.append(d_d[i][0])
    cands.append(d_d[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 15.00 seconds, 61.85 sentences/sec
tensor([0.6328, 0.6200, 0.6503, 0.6447, 0.6560, 0.6235, 0.5928, 0.6632, 0.6167,
        0.6292, 0.6026, 0.6269, 0.6484, 0.6374, 0.6565, 0.6081, 0.6482, 0.6647,
        0.6132, 0.5888, 0.6066, 0.6517, 0.6424, 0.6642, 0.6668, 0.6459, 0.6757,
        0.6715, 0.6550, 0.6387, 0.6124, 0.6092, 0.6002, 0.6100, 0.6581, 0.6577,
        0.6320, 0.6043, 0.6126, 0.5619, 0.6094, 0.6730, 0.6222, 0.6300, 0.6440,
        0.6251, 0.6317, 0.5599, 0.6397, 0.6144, 0.6261, 0.6175, 0.6396, 0.6350,
        0.6337, 0.6352, 0.6448, 0.6265, 0.6030, 0.6241, 0.6238, 0.6176, 0.6527,
        0.5961, 0.5949, 0.6547, 0.6059, 0.6175, 0.5988, 0.6186, 0.6168, 0.6490,
        0.6345, 0.5993, 0.6339, 0.6523, 0.6007, 0.5876, 0.6044, 0.6170, 0.6270,
        0.6517, 0.6429, 0.6309, 0.6503, 0.6560, 0.6409, 0.6425, 0.5910, 0.6389,
        0.6152, 0.6349, 0.6180, 0.5993, 0.6591, 0.5900, 0.6099, 0.5910, 0.5863,
        0.6547, 0.6747, 0.6387, 0.5978, 0.6186, 0.6573, 0.5948, 0.5880, 0.61

0.6214209

In [100]:
from bert_score import score

d_d = [[x,y] for x in iu_D for y in mx_D]
len(d_d)

refs=[]
cands=[]
for i in range(len(d_d)):
    refs.append(d_d[i][0])
    cands.append(d_d[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 31.47 seconds, 47.79 sentences/sec
tensor([0.5615, 0.5970, 0.6332,  ..., 0.6332, 0.6343, 0.6230])


0.61524934

In [101]:
from bert_score import score

d_d = [[x,y] for x in s_D for y in iu_D]
len(d_d)

refs=[]
cands=[]
for i in range(len(d_d)):
    refs.append(d_d[i][0])
    cands.append(d_d[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 15.51 seconds, 59.82 sentences/sec
tensor([0.6328, 0.6387, 0.6030, 0.6425, 0.6458, 0.6518, 0.6388, 0.6240, 0.6141,
        0.5831, 0.5760, 0.6368, 0.6187, 0.5975, 0.6196, 0.5613, 0.6062, 0.6678,
        0.6367, 0.6414, 0.6212, 0.6101, 0.6151, 0.6554, 0.5990, 0.6440, 0.6388,
        0.6151, 0.6076, 0.6373, 0.6449, 0.6284, 0.6200, 0.6124, 0.6241, 0.5910,
        0.5885, 0.6032, 0.5952, 0.6093, 0.6044, 0.5788, 0.5914, 0.5852, 0.6154,
        0.6203, 0.6271, 0.5755, 0.6047, 0.6105, 0.5881, 0.6078, 0.6047, 0.6178,
        0.5883, 0.5807, 0.6227, 0.6008, 0.5881, 0.5883, 0.5672, 0.6003, 0.6262,
        0.6166, 0.6503, 0.6092, 0.6238, 0.6389, 0.6182, 0.6208, 0.6125, 0.6285,
        0.6352, 0.6313, 0.6119, 0.6297, 0.6151, 0.6275, 0.6407, 0.6025, 0.6218,
        0.6392, 0.6344, 0.6484, 0.5919, 0.6341, 0.5995, 0.6316, 0.6335, 0.6447,
        0.6415, 0.5995, 0.6107, 0.6091, 0.6187, 0.6068, 0.6447, 0.6002, 0.6176,
        0.6152, 0.6129, 0.6118, 0.5932, 0.6419, 0.6597, 0.6747, 0.6370, 0.58

0.6214209

In [102]:
from bert_score import score

d_d = [[x,y] for x in s_D for y in s_D]
len(d_d)

refs=[]
cands=[]
for i in range(len(d_d)):
    refs.append(d_d[i][0])
    cands.append(d_d[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 8.48 seconds, 99.15 sentences/sec
tensor([1.0000, 0.5974, 0.6323, 0.5816, 0.5934, 0.6458, 0.6136, 0.6388, 0.5715,
        0.5840, 0.5480, 0.5986, 0.6489, 0.6199, 0.6327, 0.5788, 0.6218, 0.6393,
        0.5599, 0.6120, 0.6219, 0.6442, 0.5905, 0.6433, 0.6536, 0.6424, 0.6408,
        0.6444, 0.5949, 0.5974, 1.0000, 0.5969, 0.6000, 0.6351, 0.5688, 0.5729,
        0.6277, 0.5974, 0.5923, 0.5471, 0.6443, 0.5790, 0.6043, 0.6173, 0.5650,
        0.6448, 0.6291, 0.5634, 0.5751, 0.5743, 0.5864, 0.6098, 0.6399, 0.6165,
        0.6012, 0.6250, 0.6327, 0.6198, 0.6323, 0.5969, 1.0000, 0.6232, 0.6338,
        0.6158, 0.5838, 0.6438, 0.6007, 0.6219, 0.6000, 0.6018, 0.6250, 0.6335,
        0.6341, 0.5984, 0.6199, 0.6448, 0.5991, 0.5922, 0.6213, 0.6284, 0.6111,
        0.6463, 0.6527, 0.6377, 0.6507, 0.6521, 0.6285, 0.5816, 0.6000, 0.6232,
        1.0000, 0.6467, 0.5782, 0.5702, 0.6349, 0.6124, 0.6625, 0.6571, 0.6014,
        0.5925, 0.6115, 0.6287, 0.6243, 0.6002, 0.6349, 0.6267, 0.5762, 0.635

0.6328851

In [103]:
from bert_score import score

d_d = [[x,y] for x in s_D for y in mx_D]
len(d_d)

refs=[]
cands=[]
for i in range(len(d_d)):
    refs.append(d_d[i][0])
    cands.append(d_d[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 31.22 seconds, 43.66 sentences/sec
tensor([0.5259, 0.6128, 0.6241,  ..., 0.6458, 0.6139, 0.6297])


0.61144346

In [104]:
from bert_score import score

d_d = [[x,y] for x in mx_D for y in iu_D]
len(d_d)

refs=[]
cands=[]
for i in range(len(d_d)):
    refs.append(d_d[i][0])
    cands.append(d_d[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 29.60 seconds, 50.82 sentences/sec
tensor([0.5615, 0.5502, 0.6052,  ..., 0.6114, 0.6245, 0.6230])


0.61524934

In [105]:
from bert_score import score

d_d = [[x,y] for x in mx_D for y in s_D]
len(d_d)

refs=[]
cands=[]
for i in range(len(d_d)):
    refs.append(d_d[i][0])
    cands.append(d_d[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 30.07 seconds, 45.33 sentences/sec
tensor([0.5259, 0.5650, 0.5467,  ..., 0.6709, 0.6473, 0.6297])


0.61144346

In [106]:
from bert_score import score

d_d = [[x,y] for x in mx_D for y in mx_D]
len(d_d)

refs=[]
cands=[]
for i in range(len(d_d)):
    refs.append(d_d[i][0])
    cands.append(d_d[i][1])
    
P, R, F1 = score(cands, refs, lang="others", verbose=True)
print(F1)
f1_tensor=F1
array = f1_tensor.numpy()
array.mean()

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


calculating scores...
computing bert embedding.



computing greedy matching.



done in 22.70 seconds, 97.31 sentences/sec
tensor([1.0000, 0.5599, 0.5548,  ..., 0.6549, 0.5997, 1.0000])


0.6228754